version: 2
jobs:
  build:
    docker:
      - image: node:8

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      NODE_ENV: test

    working_directory: /home/ubuntu/workspace

    parallelism: 1

    steps:
      - checkout

      - restore_cache:
          name: Restore Cache for NPM
          keys:
            - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-{{ .Branch }}-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          name: Save Cache for NPM
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/ubuntu/workspace/node_modules

      - run:
          name: Run Test
          command: |
            npm run test
